# Generated by Django 6.0.5 on 2026-06-05 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('parent_name', models.OneToOneField(limit_choices_to={'groups__name': 'parent'}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['parent_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_surname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('student_code', models.CharField(blank=True, max_length=50)),
                ('sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('group', models.IntegerField(choices=[(0, 'Juniors'), (1, 'Seniors')])),
                ('music_option', models.IntegerField(choices=[(0, 'Beginers'), (1, 'Advanced')])),
                ('option', models.IntegerField(blank=True, choices=[(0, 'MJB'), (1, 'MJA'), (2, 'MSB'), (3, 'MSA'), (4, 'FJB'), (5, 'FJA'), (6, 'FSB'), (7, 'FSA'), (8, 'Undetermined')])),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('deregistered', models.BooleanField(default=False)),
                ('parent_name', models.ForeignKey(limit_choices_to={'groups__name': 'parent'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-group', 'student_surname'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('teacher_name', models.OneToOneField(limit_choices_to={'groups__name': 'teacher'}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
