# Generated by Django 6.0.5 on 2026-05-29 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('parent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_surname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('group', models.IntegerField(choices=[(0, 'Juniors'), (1, 'Seniors')])),
                ('music_option', models.IntegerField(choices=[(0, 'Beginers'), (1, 'Advanced')])),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('deregistered', models.BooleanField(default=False)),
                ('deregistered_on', models.DateField(blank=True)),
                ('parent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
