# Generated by Django 6.0.5 on 2026-05-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='deregistered_on',
        ),
    ]
