# Generated by Django 6.0.5 on 2026-06-06 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('room', models.IntegerField(blank=True, choices=[(0, 'English room'), (1, 'Maths room'), (2, 'Lab'), (3, 'Sports Hall'), (4, 'Gym'), (5, 'Music A'), (6, 'Music B')])),
                ('set', models.IntegerField(blank=True, choices=[(0, 'Junior'), (1, 'Senior'), (2, 'Girls'), (3, 'Boys'), (4, 'Beginner'), (5, 'Advanced')])),
                ('teacher_name', models.ForeignKey(limit_choices_to={'groups_name': 'teacher'}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
