# Generated by Django 6.0.5 on 2026-06-06 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher_name',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'teacher'}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
