# Generated by Django 6.0.5 on 2026-05-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_student_deregistered_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['parent_name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-group', 'student_surname']},
        ),
    ]
