# Generated by Django 6.0.5 on 2026-06-06 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_parent_phone_number_alter_subject_teacher_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(blank=True, choices=[(0, 'Momo'), (1, 'Moaf'), (2, 'Tumo'), (3, 'Tuaf'), (4, 'Wemo'), (5, 'Weaf'), (6, 'Thmo'), (7, 'Thaf'), (8, 'Frmo'), (9, 'Fraf')])),
                ('day', models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')])),
                ('session', models.IntegerField(blank=True, choices=[(0, 'Morning'), (1, 'Afternoon')])),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.subject')),
            ],
        ),
    ]
