# Generated by Django 6.0.5 on 2026-06-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_parent_phone_number_alter_timetable_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='group',
            field=models.IntegerField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'TBA')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], default=0),
        ),
    ]
