# Generated by Django 6.0.5 on 2026-06-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_timetable_group_alter_timetable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='music_option',
            field=models.IntegerField(choices=[(4, 'Beginers'), (5, 'Advanced')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(3, 'Male'), (2, 'Female')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='set',
            field=models.IntegerField(blank=True, choices=[(0, 'Junior'), (1, 'Senior'), (2, 'Female'), (3, 'Male'), (4, 'Beginner'), (5, 'Advanced')]),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=0),
        ),
    ]
