# Generated by Django 6.0.5 on 2026-06-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_parent_parent_name_alter_student_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='option',
            field=models.CharField(blank=True, choices=[(0, 'MJB'), (1, 'MJA'), (2, 'MSB'), (3, 'MSA'), (4, 'FJB'), (5, 'FJA'), (6, 'FSB'), (7, 'FSA')]),
        ),
    ]
