# Generated by Django 6.0.5 on 2026-06-09 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_student_music_option_alter_student_sex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mark', models.IntegerField(blank=True, choices=[(0, 'Present'), (1, 'Absent')])),
                ('reason_for_absence', models.CharField(max_length=200)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'N/A'), (1, 'Pending'), (2, 'Authorised'), (3, 'Unauthorised')])),
                ('code', models.IntegerField(blank=True, choices=[(0, 'Medical'), (1, 'Educational activity')])),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.timetable')),
                ('student_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.student')),
            ],
        ),
    ]
