# Generated by Django 6.0.5 on 2026-06-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_dailyregister'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day', 'session', 'group']},
        ),
        migrations.AlterField(
            model_name='dailyregister',
            name='reason_for_absence',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
