# Generated by Django 6.0.5 on 2026-06-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_student_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='option',
            field=models.IntegerField(blank=True, choices=[(0, 'MJB'), (1, 'MJA'), (2, 'MSB'), (3, 'MSA'), (4, 'FJB'), (5, 'FJA'), (6, 'FSB'), (7, 'FSA'), (8, 'Undetermined')]),
        ),
    ]
