# Generated by Django 6.0.5 on 2026-06-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='code',
            field=models.IntegerField(blank=True, choices=[(0, 'Medical'), (1, 'Educational activity'), (2, 'Unauthorised'), (3, 'N/A')]),
        ),
    ]
