# Generated by Django 6.0.5 on 2026-06-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_dailyregister_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyregister',
            name='reason_for_absence',
        ),
    ]
