# Generated by Django 6.0.5 on 2026-06-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
