# Generated by Django 6.0.5 on 2026-06-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_remove_dailyregister_reason_for_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='code',
            field=models.IntegerField(blank=True, choices=[(0, 'Medical'), (1, 'Educational activity'), (2, 'Unauthorised'), (3, 'N/A')], default='N/A'),
        ),
        migrations.AlterField(
            model_name='dailyregister',
            name='mark',
            field=models.IntegerField(blank=True, choices=[(0, 'Present'), (1, 'Absent'), (2, 'Not recorded')]),
        ),
        migrations.AlterField(
            model_name='dailyregister',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'N/A'), (1, 'Pending'), (2, 'Authorised'), (3, 'Unauthorised')], default='N/A'),
        ),
    ]
