# Generated by Django 6.0.5 on 2026-06-11 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_dailyregister_code_alter_dailyregister_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyregister',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyregister',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
