# Generated by Django 6.0.5 on 2026-06-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_dailyregister_date_created_alter_dailyregister_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='code',
            field=models.IntegerField(blank=True, choices=[(0, 'Medical'), (1, 'Educational activity'), (2, 'Unauthorised'), (3, ' ')], default='3'),
        ),
        migrations.AlterField(
            model_name='dailyregister',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'N/A'), (1, 'Pending'), (2, 'Authorised'), (3, 'Unauthorised')], default='0'),
        ),
    ]
