# Generated by Django 6.0.5 on 2026-06-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_alter_dailyregister_code_alter_dailyregister_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='mark',
            field=models.IntegerField(blank=True, choices=[(0, 'Present'), (1, 'Absent'), (2, ' ')], default=2),
        ),
    ]
