# Generated by Django 6.0.5 on 2026-06-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_dailyregister_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='music_option',
            field=models.IntegerField(choices=[(4, 'Beginners'), (5, 'Advanced')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
