# Generated by Django 6.0.5 on 2026-06-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_student_music_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='date',
            field=models.DateField(),
        ),
    ]
