# Generated by Django 6.0.5 on 2026-06-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.IntegerField(choices=[(0, 'Attendance below 90%'), (1, 'Attendance below 80%'), (2, 'Student missing')]),
        ),
    ]
