# Generated by Django 6.0.5 on 2026-06-15 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_email_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.email')),
            ],
        ),
    ]
