# Generated by Django 6.0.5 on 2026-06-15 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
