# Generated by Django 6.0.5 on 2026-06-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_sentemail_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyregister',
            name='reason_for_absence',
            field=models.TextField(default=' '),
        ),
    ]
