# Generated by Django 6.0.5 on 2026-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_alter_timetable_group_alter_timetable_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='reason_for_absence',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
