# Generated by Django 6.0.5 on 2026-06-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_alter_dailyregister_reason_for_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='reason_for_absence',
            field=models.TextField(blank=True),
        ),
    ]
