# Generated by Django 6.0.5 on 2026-06-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_alter_dailyregister_reason_for_absence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyregister',
            options={'ordering': ['student_code', 'date']},
        ),
    ]
