# Generated by Django 6.0.5 on 2026-06-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_alter_dailyregister_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyregister',
            options={'ordering': ['date', 'student_code']},
        ),
    ]
