# Generated by Django 6.0.5 on 2026-06-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='mark',
            field=models.IntegerField(choices=[(0, 'Present'), (1, 'Absent'), (2, 'Not recorded ')], default=2),
        ),
    ]
