# Generated by Django 6.0.5 on 2026-06-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_alter_dailyregister_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.IntegerField(choices=[(0, 'Attendance below 90%'), (1, 'Attendance below 80%'), (2, 'Student missing'), (3, 'Unauthorised absence')]),
        ),
    ]
