# Generated by Django 6.0.5 on 2026-06-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_alter_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='deregistered_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
