# Generated by Django 6.0.5 on 2026-06-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_alter_student_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
