# Generated by Django 6.0.5 on 2026-07-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_alter_subject_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='code',
            field=models.IntegerField(blank=True, choices=[(0, 'Medical'), (1, 'Educational activity'), (2, 'Unauthorised'), (3, ' ')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='dailyregister',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'N/A'), (1, 'Pending'), (2, 'Authorised'), (3, 'Unauthorised')], default=0, null=True),
        ),
    ]
