# Generated by Django 6.0.5 on 2026-07-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0035_alter_dailyregister_code_alter_dailyregister_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='status',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Pending'), (2, 'Authorised'), (3, 'Unauthorised')], default=0),
        ),
    ]
