# Generated by Django 6.0.5 on 2026-07-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_alter_dailyregister_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='code',
            field=models.IntegerField(choices=[(0, 'Medical'), (1, 'Educational activity'), (2, 'Unauthorised'), (3, ' ')], default=3),
        ),
    ]
