# Generated by Django 6.0.5 on 2026-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0039_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='code',
            field=models.IntegerField(choices=[(0, 'Medical'), (1, 'Educational activity'), (2, 'Unauthorised'), (3, '-- ')], default=3),
        ),
    ]
